In [ ]:
#import pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import warnings

In [ ]:

# Suppress warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
VERBOSE = 0

In [ ]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.12.4)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.5.0)

In [ ]:
!pip install --upgrade numpy pandas

In [ ]:
from typing import Dict, List, Tuple

from flwr.common import Metrics

In [ ]:
!pip uninstall -y pandas numpy
!pip install pandas numpy

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
!pip install numpy==1.24.4

Collecting numpy==1.24.4
  Downloading numpy-1.24.4-cp310-cp310-win_amd64.whl (14.8 MB)
     -------------------------------------- 14.8/14.8 MB 667.0 kB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Thao Tran\\anaconda3\\Lib\\site-packages\\~.mpy\\fft\\_pocketfft_internal.cp310-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [ ]:


print("NumPy version:", np.__version__)

NumPy version: 1.26.4

In [ ]:
print("Pandas version:", pd.__version__)

Pandas version: 2.2.2

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
#Preprocessing function for one dataset
def preprocess_dataset(data_path, columns, target_column):
    df=pd.read_csv(data_path)
    #Select relevant columns
    df_cols=df[columns]
    def balance_classes_with_smote(data_df):
        features= data_df.drop(columns=target_column)
        labels=data_df[target_column]
        #Apply SMOTE to oversammple the minority class
        smote= SMOTE(random_state=1)
        features_resampled, labels_resampled = smote.fit_resample(features, labels)
        return pd.DataFrame(features_resampled,columns=features.columns), pd.Series(labels_resampled,name=target_column)
    #One-hot encoding and scaling
    df_encoded=pd.get_dummies(df_cols)
    #Apply SMOTE to handle class imbalance
    features_balanced, labels_balanced = balance_classes_with_smote(df_encoded)
    scaler=MinMaxScaler()
    features_scaled=pd.DataFrame(scaler.fit_transform(features_balanced), columns=features_balanced.columns)
    #Combine features and labels
    df_scaled=pd.concat([features_scaled, labels_balanced],axis=1)

    #Split into train and test
   # train_df, test_df=train_test_split(df_scaled, test_size=0.1, random_state=42)
    return df_scaled

In [ ]:
#Upload and preprocess credit_application_data
credit_application_scaled= preprocess_dataset("/content/application_data.csv",['AMT_CREDIT','AMT_INCOME_TOTAL','NAME_CONTRACT_TYPE','TARGET'],'TARGET')

In [ ]:
train_df, test_df = train_test_split(credit_application_scaled, test_size=0.1, random_state=42)

In [ ]:
# Convert to numpy arrays
train_features = train_df.drop(columns=["TARGET"]).values
train_labels = train_df["TARGET"].values
test_features = test_df.drop(columns=["TARGET"]).values
test_labels = test_df["TARGET"].values

# Combine features and labels for the training dataset
train_data = np.concatenate((train_features, train_labels.reshape(-1, 1)), axis=1)

# Combine features and labels for the test dataset
test_data = np.concatenate((test_features, test_labels.reshape(-1, 1)), axis=1)

# Ensure that data is in float32 format for TensorFlow compatibility
train_data = train_data.astype(np.float32)
test_data = test_data.astype(np.float32)

# Create Partitions for federated learning
num_partitions = 10
partitions = []
partition_size = len(train_data) // num_partitions

for i in range(num_partitions):
    start_idx = i * partition_size
    end_idx = (i + 1) * partition_size
    partition_data = train_data[start_idx:end_idx]
    partitions.append(partition_data)

NUM_CLIENTS = num_partitions

# Number of samples in train and test data
num_train_samples = train_data.shape[0]
num_test_samples = test_data.shape[0]
print(f"Number of samples in train data: {num_train_samples}")
print(f"Number of samples in test data: {num_test_samples}")

Number of samples in train data: 508834
Number of samples in test data: 56538

In [ ]:
credit_application_scaled.head()

,AMT_CREDIT,AMT_INCOME_TOTAL,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,TARGET
0,0.090287,0.001512,1.0,0.0,1
1,0.311736,0.002089,1.0,0.0,0
2,0.022472,0.000358,0.0,1.0,0
3,0.066837,0.000935,1.0,0.0,0
4,0.116854,0.000819,1.0,0.0,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
/content/application_data.csv

In [ ]:
credit_application_scaled=

In [ ]:
#Upload and preprocess creditcard_2023
creditcard_2023_scaled=preprocess_dataset("C:\\Users\\Thao Tran\\Downloads\\archive (8)\\creditcard_2023.csv",["Class","V1","V2","Amount"],'Class')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Thao Tran\\Downloads\\archive (8)\\creditcard_2023.csv'

In [ ]:
#Upload and preprocess creditcard
creditcard_scaled=preprocess_dataset("C:\\Users\\Thao Tran\\Downloads\\archive (9)\\creditcard.csv",["Class","V1","V2","Amount"],'Class')

In [ ]:
#Upload and preprocess SAML_D
samld_scaled=preprocess_dataset("C:\\Users\\Thao Tran\\Downloads\\archive (10)\\SAML-D.csv",["Sender_account","Receiver_account","Payment_type","Amount","Is_laundering"],'Is_laundering')

In [ ]:
credit_application_scaled.head()

,AMT_CREDIT,AMT_INCOME_TOTAL,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,TARGET
0,0.090287,0.001512,1.0,0.0,1
1,0.311736,0.002089,1.0,0.0,0
2,0.022472,0.000358,0.0,1.0,0
3,0.066837,0.000935,1.0,0.0,0
4,0.116854,0.000819,1.0,0.0,0

In [ ]:
samld_scaled.head()

,Sender_account,Receiver_account,Amount,Payment_type_ACH,Payment_type_Cash Deposit,Payment_type_Cash Withdrawal,Payment_type_Cheque,Payment_type_Credit card,Payment_type_Cross-border,Payment_type_Debit card,Is_laundering
0,0.872474,0.276936,0.000115,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,0.149198,0.840128,0.000477,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2,0.028730,0.440477,0.001135,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
3,0.537666,0.960045,0.000942,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.961420,0.380334,0.000009,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
creditcard_scaled.head()

         V1        V2    Amount  Class
0  0.935192  0.766490  0.005824      0
1  0.978542  0.770067  0.000105      0
2  0.935217  0.753118  0.014739      0
3  0.941878  0.765304  0.004807      0
4  0.938617  0.776520  0.002724      0

In [ ]:
creditcard_2023_scaled.head()

         V1        V2    Amount  Class
0  0.565091  0.911068  0.747484      0
1  0.782703  0.913159  0.270170      0
2  0.565157  0.902238  0.102690      0
3  0.584043  0.910345  0.222361      0
4  0.574494  0.916671  0.593122      0

In [ ]:
credit_application_data['TARGET'].value_counts(normalize=True) * 100

TARGET
0    91.927118
1     8.072882
Name: proportion, dtype: float64

In [ ]:
creditcard_2023=pd.read_csv("C:\\Users\\Thao Tran\\Downloads\\archive (8)\\creditcard_2023.csv")

In [ ]:
creditcard_2023['Class'].value_counts(normalize=True) * 100

Class
0    50.0
1    50.0
Name: proportion, dtype: float64

In [ ]:
creditcard=pd.read_csv("C:\\Users\Thao Tran\\Downloads\\archive (9)\\creditcard.csv")

In [ ]:
creditcard['Class'].value_counts(normalize=True) * 100

Class
0    99.827251
1     0.172749
Name: proportion, dtype: float64

In [ ]:
SAML_D=pd.read_csv("C:\\Users\\Thao Tran\\Downloads\\archive (10)\\SAML-D.csv")

In [ ]:
SAML_D.head(5)

,Time,Date,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering,Laundering_type
0,10:35:19,2022-10-07,8724731955,2769355426,1459.15,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits
1,10:35:20,2022-10-07,1491989064,8401255335,6019.64,UK pounds,Dirham,UK,UAE,Cross-border,0,Normal_Fan_Out
2,10:35:20,2022-10-07,287305149,4404767002,14328.44,UK pounds,UK pounds,UK,UK,Cheque,0,Normal_Small_Fan_Out
3,10:35:21,2022-10-07,5376652437,9600420220,11895.00,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Fan_In
4,10:35:21,2022-10-07,9614186178,3803336972,115.25,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits

In [ ]:
SAML_D['Is_laundering'].value_counts(normalize=True) * 100

Is_laundering
0    99.896127
1     0.103873
Name: proportion, dtype: float64

## Federated Learning Model setup

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\thao tran\anaconda3\lib\site-packages (2.18.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.3.25)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.28.1)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)
Requirement already satisfied: setuptools in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (65.6.3)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.12.2)
Requirement already satisfied: libclang>=13.0.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (5.28.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.12.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.31.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)
Requirement already satisfied: packaging in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (22.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.6.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.68.0)
Collecting numpy<2.1.0,>=1.26.0
  Using cached numpy-2.0.2-cp310-cp310-win_amd64.whl (15.9 MB)
Requirement already satisfied: six>=1.12.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.14.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\thao tran\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.38.4)
Requirement already satisfied: rich in c:\users\thao tran\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\thao tran\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\thao tran\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.13.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\thao tran\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\thao tran\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\thao tran\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\thao tran\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.0.4)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (2.2.2)
Requirement already satisfied: markdown>=2.6.8 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\thao tran\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\thao tran\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (2.1.1)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\thao tran\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\thao tran\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\thao tran\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.2)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Thao Tran\\anaconda3\\Lib\\site-packages\\~-mpy.libs\\libscipy_openblas64_-c16e4918366c6bc1f1cd71e28ca36fc0.dll'
Consider using the `--user` option or check the permissions.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1

In [ ]:
!pip install flwr

Collecting flwr
  Downloading flwr-1.13.1-py3-none-any.whl.metadata (15 kB)
Collecting cryptography<43.0.0,>=42.0.4 (from flwr)
  Downloading cryptography-42.0.8-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting grpcio!=1.64.2,<2.0.0,<=1.64.3,>=1.60.0 (from flwr)
  Downloading grpcio-1.64.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.3 kB)
Collecting iterators<0.0.3,>=0.0.2 (from flwr)
  Downloading iterators-0.0.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from flwr) (1.26.4)
Collecting pathspec<0.13.0,>=0.12.1 (from flwr)
  Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: protobuf<5.0.0,>=4.25.2 in /usr/local/lib/python3.10/dist-packages (from flwr) (4.25.5)
Collecting pycryptodome<4.0.0,>=3.18.0 (from flwr)
  Downloading pycryptodome-3.21.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: rich<14.0.0,>=13.5.0 in /usr/local/lib/python3.10/dist-packages (from flwr) (13.9.4)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from flwr) (2.2.1)
Collecting tomli-w<2.0.0,>=1.0.0 (from flwr)
  Downloading tomli_w-1.1.0-py3-none-any.whl.metadata (5.7 kB)
Collecting typer<0.13.0,>=0.12.5 (from flwr)
  Downloading typer-0.12.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography<43.0.0,>=42.0.4->flwr) (1.17.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0.0,>=13.5.0->flwr) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0.0,>=13.5.0->flwr) (2.18.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0.0,>=13.5.0->flwr) (4.12.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<0.13.0,>=0.12.5->flwr) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<0.13.0,>=0.12.5->flwr) (1.5.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography<43.0.0,>=42.0.4->flwr) (2.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.5.0->flwr) (0.1.2)
Downloading flwr-1.13.1-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.2/512.2 kB 11.7 MB/s eta 0:00:00
Downloading cryptography-42.0.8-cp39-abi3-manylinux_2_28_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 69.1 MB/s eta 0:00:00
Downloading grpcio-1.64.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 76.2 MB/s eta 0:00:00
Downloading iterators-0.0.2-py3-none-any.whl (3.9 kB)
Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Downloading pycryptodome-3.21.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 65.5 MB/s eta 0:00:00
Downloading tomli_w-1.1.0-py3-none-any.whl (6.4 kB)
Downloading typer-0.12.5-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: tomli-w, pycryptodome, pathspec, iterators, grpcio, cryptography, typer, flwr
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.68.1
    Uninstalling grpcio-1.68.1:
      Successfully uninstalled grpcio-1.68.1
  Attempting uninstall: cryptography
    Found existing installation: cryptography 43.0.3
    Uninstalling cryptography-43.0.3:
      Successfully uninstalled cryptography-43.0.3
  Attempting uninstall: typer
    Found existing installation: typer 0.15.0
    Uninstalling typer-0.15.0:
      Successfully uninstalled typer-0.15.0
Successfully installed cryptography-42.0.8 flwr-1.13.1 grpcio-1.64.3 iterators-0.0.2 pathspec-0.12.1 pycryptodome-3.21.0 tomli-w-1.1.0 typer-0.12.5

In [ ]:
import flwr as fl
print(fl.__version__)

1.13.1

In [ ]:
!pip install --upgrade --force-reinstall flwr

Collecting flwr
  Using cached flwr-1.13.1-py3-none-any.whl (512 kB)
Collecting grpcio!=1.64.2,<2.0.0,<=1.64.3,>=1.60.0
  Using cached grpcio-1.64.3-cp310-cp310-win_amd64.whl (4.0 MB)
Collecting numpy<3.0.0,>=1.26.0
  Using cached numpy-2.1.3-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting rich<14.0.0,>=13.5.0
  Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Collecting tomli<3.0.0,>=2.0.1
  Downloading tomli-2.2.1-py3-none-any.whl (14 kB)
Collecting pathspec<0.13.0,>=0.12.1
  Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting tomli-w<2.0.0,>=1.0.0
  Using cached tomli_w-1.1.0-py3-none-any.whl (6.4 kB)
Collecting iterators<0.0.3,>=0.0.2
  Using cached iterators-0.0.2-py3-none-any.whl (3.9 kB)
Collecting protobuf<5.0.0,>=4.25.2
  Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl (413 kB)
Collecting typer<0.13.0,>=0.12.5
  Using cached typer-0.12.5-py3-none-any.whl (47 kB)
Collecting pycryptodome<4.0.0,>=3.18.0
  Using cached pycryptodome-3.21.0-cp36-abi3-win_amd64.whl (1.8 MB)
Collecting cryptography<43.0.0,>=42.0.4
  Using cached cryptography-42.0.8-cp39-abi3-win_amd64.whl (2.9 MB)
Collecting cffi>=1.12
  Downloading cffi-1.17.1-cp310-cp310-win_amd64.whl (181 kB)
     ------------------------------------ 181.3/181.3 kB 914.8 kB/s eta 0:00:00
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Collecting typing-extensions<5.0,>=4.0.0
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting shellingham>=1.3.0
  Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting click>=8.0.0
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ---------------------------------------- 97.9/97.9 kB 1.4 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     -------------------------------------- 117.6/117.6 kB 2.3 MB/s eta 0:00:00
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: typing-extensions, tomli-w, tomli, shellingham, pygments, pycryptodome, pycparser, protobuf, pathspec, numpy, mdurl, iterators, grpcio, colorama, markdown-it-py, click, cffi, rich, cryptography, typer, flwr
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: tomli-w
    Found existing installation: tomli_w 1.1.0
    Uninstalling tomli_w-1.1.0:
      Successfully uninstalled tomli_w-1.1.0
  Attempting uninstall: tomli
    Found existing installation: tomli 2.0.1
    Uninstalling tomli-2.0.1:
      Successfully uninstalled tomli-2.0.1
  Attempting uninstall: shellingham
    Found existing installation: shellingham 1.5.4
    Uninstalling shellingham-1.5.4:
      Successfully uninstalled shellingham-1.5.4
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.18.0
    Uninstalling Pygments-2.18.0:
      Successfully uninstalled Pygments-2.18.0
  Attempting uninstall: pycryptodome
    Found existing installation: pycryptodome 3.21.0
    Uninstalling pycryptodome-3.21.0:
      Successfully uninstalled pycryptodome-3.21.0
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.21
    Uninstalling pycparser-2.21:
      Successfully uninstalled pycparser-2.21
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.5
    Uninstalling protobuf-4.25.5:
      Successfully uninstalled protobuf-4.25.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Thao Tran\\anaconda3\\Lib\\site-packages\\google\\~-pb\\_message.pyd'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\thao tran\anaconda3\lib\site-packages)

In [ ]:
import tensorflow as tf
def get_model():
    """Construct a simple binary classification model"""
    model= tf.keras.models.Sequential([
        tf.keras.layers.Dense(128,activation='relu',input_shape=(train_data.shape[1]-1,)),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1,activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return model

In [ ]:
#FlowerClient class

from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
class FlowerClient(fl.client.NumPyClient):
    def __init__(self,model,trainset,valset) -> None:
        self.model=get_model()
        self.trainset = trainset
        self.valset= valset
    def get_parameters(self,config):
        return self.model.get_weights()

    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        train_features = self.trainset[:, :-1]
        train_labels = self.trainset[:, -1]
        self.model.fit(train_features, train_labels, epochs=1, verbose=0)

        return self.model.get_weights(), len(train_features), {}

    def evaluate(self, parameters, config):

        self.model.set_weights(parameters)

        val_features = self.valset[:, :-1]  #Extract features

        val_labels = self.valset[:, -1] #Extract labels
        predictions=self.model.predict(val_features)
        predicted_labels = (predictions >0.5).astype(int)

        loss, acc = self.model.evaluate(val_features, val_labels, verbose=0)
    # Calculate precision, recall, and F1-score
        precision = precision_score(val_labels,predicted_labels)
        recall =recall_score(val_labels, predicted_labels)
        f1= f1_score(val_labels,predicted_labels)
        #Print a classification report for detailed metrics
        print(classification_report(val_labels,predicted_labels))
        #Return loss and metrics

        return loss, len(val_features), {"accuracy": acc,"precision":precision, "recall": recall,"f1-score":f1}

In [ ]:
# Weighted average for aggregation of metrics
def weighted_average(metrics: List[Tuple[int, Metrics]]) -> Metrics:
    accuracies = [num_examples * m["accuracy"] for num_examples, m in metrics]
    precisions = [num_examples * m["precision"] for num_examples, m in metrics]
    recalls = [num_examples * m["recall"] for num_examples, m in metrics]
    f1_scores = [num_examples * m["f1_score"] for num_examples, m in metrics]
    examples = [num_examples for num_examples, _ in metrics]

    # Aggregate and return custom metrics (weighted average)
    return {
        "accuracy": sum(accuracies) / sum(examples),
        "precision": sum(precisions) / sum(examples),
        "recall": sum(recalls) / sum(examples),
        "f1_score": sum(f1_scores) / sum(examples)
    }

# Function to create clients
def get_client_fn(partitions: List[np.ndarray], testset: np.ndarray):
    def client_fn(cid: str) -> fl.client.Client:
        model=get_model()
        partition = partitions[int(cid)]
        trainset, valset = partition, testset
        return FlowerClient(model,trainset, valset)
    return client_fn

def get_evaluate_fn(testset: np.ndarray):
    def evaluate(server_round: int, parameters: fl.common.NDArray, config: Dict[str, fl.common.Scalar]):
        model = get_model()
        model.set_weights(parameters)
        val_features = testset[:, :-1]
        val_labels = testset[:, -1]
        loss, accuracy = model.evaluate(val_features, val_labels, verbose=VERBOSE)

        # Add additional metrics calculations here
        predictions = (model.predict(val_features) > 0.5).astype(int)
        precision = precision_score(val_labels, predictions)
        recall = recall_score(val_labels, predictions)
        f1 = f1_score(val_labels, predictions)

        # Return aggregated metrics
        return loss, {"accuracy": accuracy, "precision": precision, "recall": recall, "f1_score": f1}
    return evaluate

In [ ]:
# Create FedAvg strategy
strategy = fl.server.strategy.FedAvg(
    fraction_fit=0.1,
    fraction_evaluate=0.05,
    min_fit_clients=10,
    min_evaluate_clients=5,
    min_available_clients=int(NUM_CLIENTS * 0.75),
    evaluate_fn=get_evaluate_fn(test_data),  # This should include precision, recall, and F1-score
    evaluate_metrics_aggregation_fn=weighted_average
)

# Define the resources each client should use
client_resources = {
    "num_cpus": 2,  # Allocate 1 CPU per client (adjust based on your system)
    "num_gpus": 0.5  # Allocate 10% of a GPU per client (if you're using GPUs)
}

# Run the Flower simulation
history = fl.simulation.start_simulation(
    client_fn=get_client_fn(partitions, test_data),
    num_clients=NUM_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=10),
    strategy=strategy,
    client_resources=client_resources
)

# After training, you'll have the aggregated precision, recall, and F1-score
print("Final metrics:", history)

WARNING :
Setting `min_available_clients` lower than `min_fit_clients` or
`min_evaluate_clients` can cause the server to fail when there are too few clients
connected to the server. `min_available_clients` must be set to a value larger
than or equal to the values of `min_fit_clients` and `min_evaluate_clients`.

WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=10, no round_timeout
2024-12-09 05:21:18,270	INFO worker.py:1752 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'memory': 7917173147.0, 'object_store_memory': 3958586572.0, 'GPU': 1.0, 'node:172.28.0.12': 1.0, 'CPU': 2.0, 'accelerator_type:T4': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
INFO :      [INIT]
INFO :      Requesting initial parameters from one random client
(pid=16599) 2024-12-09 05:21:22.322293: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=16599) 2024-12-09 05:21:22.359109: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=16599) 2024-12-09 05:21:22.369287: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=16599) 2024-12-09 05:21:24.065238: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) /usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
(ClientAppActor pid=16599)   super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(ClientAppActor pid=16599) I0000 00:00:1733721685.829496   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.890642   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.890912   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.891577   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.891832   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.891984   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.971926   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) I0000 00:00:1733721685.972187   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
(ClientAppActor pid=16599) 2024-12-09 05:21:25.972315: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(ClientAppActor pid=16599) I0000 00:00:1733721685.972421   16599 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
INFO :      Received initial parameters from one random client
INFO :      Starting evaluation of initial global parameters
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

INFO :      initial parameters (loss, other metrics): 0.695139467716217, {'accuracy': 0.4966924786567688, 'precision': 0.49669249000672117, 'recall': 1.0, 'f1_score': 0.6637201607185063}
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(ClientAppActor pid=16599) I0000 00:00:1733721696.322126   16691 service.cc:146] XLA service 0x78297c0073c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(ClientAppActor pid=16599) I0000 00:00:1733721696.322179   16691 service.cc:154]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
(ClientAppActor pid=16599) I0000 00:00:1733721698.009186   16691 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.
INFO :      aggregate_fit: received 10 results and 0 failures
WARNING :   No fit_metrics_aggregation_fn provided
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

INFO :      fit progress: (1, 0.680432140827179, {'accuracy': 0.5499310493469238, 'precision': 0.5337015444410351, 'recall': 0.7432519051349619, 'f1_score': 0.6212829290072928}, 55.46456195300016)
INFO :      configure_evaluate: strategy sampled 5 clients (out of 10)
(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

   1/1767 ━━━━━━━━━━━━━━━━━━━━ 5:03 172ms/step
 100/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 204/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 996us/step
 304/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 356/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 997us/step
 460/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 990us/step
 559/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 995us/step
 662/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 994us/step
 761/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 997us/step
 826/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 883/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 943/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1009/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1077/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1138/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1204/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1267/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1335/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1407/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1475/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1539/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1598/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1661/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1727/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1758/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1767/1767 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step
(ClientAppActor pid=16599)               precision    recall  f1-score   support
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)          0.0       0.59      0.36      0.45     28456
(ClientAppActor pid=16599)          1.0       0.53      0.74      0.62     28082
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)     accuracy                           0.55     56538
(ClientAppActor pid=16599)    macro avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599) weighted avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599)

(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) /usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
(ClientAppActor pid=16599)   super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

  52/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 151/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 255/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 994us/step
 353/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 454/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 543/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 646/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 743/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 840/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 938/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1039/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1138/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1238/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1328/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1431/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1524/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1621/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1721/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
(ClientAppActor pid=16599)               precision    recall  f1-score   support
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)          0.0       0.59      0.36      0.45     28456
(ClientAppActor pid=16599)          1.0       0.53      0.74      0.62     28082
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)     accuracy                           0.55     56538
(ClientAppActor pid=16599)    macro avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599) weighted avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599)

(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) /usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
(ClientAppActor pid=16599)   super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

  49/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 149/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 241/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 339/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 436/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 538/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 591/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 691/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 793/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 892/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 995/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1096/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1195/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1289/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1390/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1473/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1571/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1673/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1721/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
(ClientAppActor pid=16599)               precision    recall  f1-score   support
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)          0.0       0.59      0.36      0.45     28456
(ClientAppActor pid=16599)          1.0       0.53      0.74      0.62     28082
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)     accuracy                           0.55     56538
(ClientAppActor pid=16599)    macro avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599) weighted avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599)

(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) /usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
(ClientAppActor pid=16599)   super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

  51/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 154/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 990us/step
 245/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 344/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 447/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 549/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 649/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 747/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 851/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 954/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1057/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1156/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1247/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1347/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1446/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1545/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1644/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1746/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
(ClientAppActor pid=16599)               precision    recall  f1-score   support
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)          0.0       0.59      0.36      0.45     28456
(ClientAppActor pid=16599)          1.0       0.53      0.74      0.62     28082
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)     accuracy                           0.55     56538
(ClientAppActor pid=16599)    macro avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599) weighted avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599)

(ClientAppActor pid=16599) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)             This is a deprecated feature. It will be removed
(ClientAppActor pid=16599)             entirely in future versions of Flower.
(ClientAppActor pid=16599)
(ClientAppActor pid=16599) /usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
(ClientAppActor pid=16599)   super().__init__(activity_regularizer=activity_regularizer, **kwargs)
(ClientAppActor pid=16599) WARNING :   Deprecation Warning: The `client_fn` function must return an instance of `Client`, but an instance of `NumpyClient` was returned. Please use `NumPyClient.to_client()` method to convert it to `Client`.

   1/1767 ━━━━━━━━━━━━━━━━━━━━ 3:30 119ms/step
  96/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 196/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 298/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 403/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 501/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 603/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 703/1767 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
 799/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 897/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
 988/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1086/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1185/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1336/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1385/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1487/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1537/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1637/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1738/1767 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
1767/1767 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

INFO :      aggregate_evaluate: received 5 results and 0 failures
ERROR :     'f1_score'
ERROR :     Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/legacy_app.py", line 359, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 145, in fit
    res_fed = self.evaluate_round(server_round=current_round, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 203, in evaluate_round
    ] = self.strategy.aggregate_evaluate(server_round, results, failures)
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/strategy/fedavg.py", line 281, in aggregate_evaluate
    metrics_aggregated = self.evaluate_metrics_aggregation_fn(eval_metrics)
  File "<ipython-input-39-93880e6b9ff3>", line 6, in weighted_average
    f1_scores = [num_examples * m["f1_score"] for num_examples, m in metrics]
  File "<ipython-input-39-93880e6b9ff3>", line 6, in <listcomp>
    f1_scores = [num_examples * m["f1_score"] for num_examples, m in metrics]
  File "/usr/local/lib/python3.10/dist-packages/flwr/common/record/typeddict.py", line 50, in __getitem__
    return cast(dict[K, V], self.__dict__["_data"])[item]
KeyError: 'f1_score'

ERROR :     Your simulation crashed :(. This could be because of several reasons. The most common are:
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example:
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because:
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0.5} is not enough for your run). Use fewer concurrent actors.
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0.5}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.

(ClientAppActor pid=16599)               precision    recall  f1-score   support
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)          0.0       0.59      0.36      0.45     28456
(ClientAppActor pid=16599)          1.0       0.53      0.74      0.62     28082
(ClientAppActor pid=16599)
(ClientAppActor pid=16599)     accuracy                           0.55     56538
(ClientAppActor pid=16599)    macro avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599) weighted avg       0.56      0.55      0.53     56538
(ClientAppActor pid=16599)

RuntimeError: Simulation crashed.